#pragma once
#include <functional>
#include <memory>
#include <string>
#include <vector>
#include <list>
#include <map>
#include <cassert>
#include <iostream>
#include <ctype.h>
#include <stdlib.h>
#include "../deps/xjson/include/xjson.hpp"
#include "../deps/xtest/include/xtest.hpp"
#include "store/xson_t.hpp"
#include "store/xstore.hpp"
